name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        env:
          REPOSITORY_NAME: ${{ github.repository }}
        run: |
          REPO_NAME=$(echo $REPOSITORY_NAME | cut -d'/' -f2)
          npm run build --prod

      - name: Log build directory structure
        run: ls -R dist/relic-query/browser
    
      - name: Move build output to docs
        run: |
          mkdir docs
          mv dist/relic-query/browser/* docs

      - name: Rename index.html to 404.html
        run: cp docs/index.html docs/404.html

      - name: Log build directory structure
        run: ls -R docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs