name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        env:
          REPOSITORY_NAME: ${{ github.repository }}
        run: |
          REPO_NAME=$(echo $REPOSITORY_NAME | cut -d'/' -f2)
          npm run build --production --output-path docs --base-href /$REPO_NAME/

      - name: Rename index.html to 404.html
        run: mv docs/index.html docs/404.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs